parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-23-23-195-205.compute-1.amazonaws.com
    database_port: 5432
    database_name: dcse965hnlciah
    database_user: jmdzikonmzpmjq
    database_password: 235c0841e25cc674f1980422eeea901ce99b76ea52626354b718fe9d9ed1e330
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
