app_payement:
    resource: "@AppBundle/Resources/config/routing/commande.yml"
    prefix:   /payement  


homepage:
    path:     /
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET

helppage:
    path:     /help.{page}.html
    defaults: { _controller: "AppBundle:App:help" }
    methods:  GET




